// ============ PATIENTS ============
export const patients = [
  {
    id: "P001",
    name: "John Smith",
    age: 45,
    gender: "Male",
    contact: "+1 (555) 123-4567",
    email: "john.smith@email.com",
    address: "123 Oak Street, Springfield, IL",
    bloodGroup: "O+",
    department: "Cardiology",
    assignedDoctor: "Dr. Sarah Wilson",
    status: "Active",
    admissionDate: "2026-01-15",
    medicalHistory: [
      { date: "2025-12-01", diagnosis: "Hypertension", treatment: "Prescribed Amlodipine 5mg", doctor: "Dr. Sarah Wilson" },
      { date: "2025-10-15", diagnosis: "Chest Pain", treatment: "ECG and Blood Tests", doctor: "Dr. Sarah Wilson" },
      { date: "2025-06-20", diagnosis: "Routine Checkup", treatment: "All vitals normal", doctor: "Dr. James Brown" },
    ],
    vitals: { bp: "130/85", heartRate: "78 bpm", temperature: "98.6°F", weight: "82 kg" },
  },
  {
    id: "P002",
    name: "Emily Johnson",
    age: 32,
    gender: "Female",
    contact: "+1 (555) 234-5678",
    email: "emily.j@email.com",
    address: "456 Maple Ave, Chicago, IL",
    bloodGroup: "A+",
    department: "Orthopedics",
    assignedDoctor: "Dr. Michael Chen",
    status: "Active",
    admissionDate: "2026-02-01",
    medicalHistory: [
      { date: "2026-01-20", diagnosis: "Knee Injury", treatment: "MRI Scan and Physiotherapy", doctor: "Dr. Michael Chen" },
      { date: "2025-11-10", diagnosis: "Back Pain", treatment: "X-ray and Pain Management", doctor: "Dr. Michael Chen" },
    ],
    vitals: { bp: "120/80", heartRate: "72 bpm", temperature: "98.4°F", weight: "65 kg" },
  },
  {
    id: "P003",
    name: "Robert Davis",
    age: 58,
    gender: "Male",
    contact: "+1 (555) 345-6789",
    email: "robert.d@email.com",
    address: "789 Pine Road, Springfield, IL",
    bloodGroup: "B+",
    department: "Neurology",
    assignedDoctor: "Dr. Lisa Park",
    status: "Discharged",
    admissionDate: "2026-01-05",
    medicalHistory: [
      { date: "2026-01-05", diagnosis: "Migraine", treatment: "CT Scan and Medication", doctor: "Dr. Lisa Park" },
      { date: "2025-09-12", diagnosis: "Dizziness", treatment: "Vestibular Testing", doctor: "Dr. Lisa Park" },
    ],
    vitals: { bp: "140/90", heartRate: "82 bpm", temperature: "98.8°F", weight: "90 kg" },
  },
  {
    id: "P004",
    name: "Maria Garcia",
    age: 28,
    gender: "Female",
    contact: "+1 (555) 456-7890",
    email: "maria.g@email.com",
    address: "321 Elm Street, Aurora, IL",
    bloodGroup: "AB+",
    department: "Dermatology",
    assignedDoctor: "Dr. Amanda Lee",
    status: "Active",
    admissionDate: "2026-02-05",
    medicalHistory: [
      { date: "2026-02-05", diagnosis: "Eczema", treatment: "Topical Steroid Cream", doctor: "Dr. Amanda Lee" },
    ],
    vitals: { bp: "115/75", heartRate: "70 bpm", temperature: "98.2°F", weight: "58 kg" },
  },
  {
    id: "P005",
    name: "David Wilson",
    age: 67,
    gender: "Male",
    contact: "+1 (555) 567-8901",
    email: "david.w@email.com",
    address: "654 Cedar Lane, Naperville, IL",
    bloodGroup: "O-",
    department: "Cardiology",
    assignedDoctor: "Dr. Sarah Wilson",
    status: "Critical",
    admissionDate: "2026-02-08",
    medicalHistory: [
      { date: "2026-02-08", diagnosis: "Cardiac Arrest", treatment: "Emergency CPR, ICU Admission", doctor: "Dr. Sarah Wilson" },
      { date: "2025-08-15", diagnosis: "Coronary Artery Disease", treatment: "Angioplasty", doctor: "Dr. Sarah Wilson" },
    ],
    vitals: { bp: "150/95", heartRate: "92 bpm", temperature: "99.1°F", weight: "78 kg" },
  },
  {
    id: "P006",
    name: "Sarah Thompson",
    age: 41,
    gender: "Female",
    contact: "+1 (555) 678-9012",
    email: "sarah.t@email.com",
    address: "987 Birch Blvd, Evanston, IL",
    bloodGroup: "A-",
    department: "Gynecology",
    assignedDoctor: "Dr. Rachel Green",
    status: "Active",
    admissionDate: "2026-01-28",
    medicalHistory: [
      { date: "2026-01-28", diagnosis: "Routine Checkup", treatment: "All reports normal", doctor: "Dr. Rachel Green" },
    ],
    vitals: { bp: "118/76", heartRate: "74 bpm", temperature: "98.5°F", weight: "62 kg" },
  },
  {
    id: "P007",
    name: "James Anderson",
    age: 53,
    gender: "Male",
    contact: "+1 (555) 789-0123",
    email: "james.a@email.com",
    address: "147 Walnut St, Joliet, IL",
    bloodGroup: "B-",
    department: "Gastroenterology",
    assignedDoctor: "Dr. James Brown",
    status: "Active",
    admissionDate: "2026-02-03",
    medicalHistory: [
      { date: "2026-02-03", diagnosis: "Gastric Ulcer", treatment: "Endoscopy and PPI Medication", doctor: "Dr. James Brown" },
    ],
    vitals: { bp: "125/82", heartRate: "76 bpm", temperature: "98.7°F", weight: "85 kg" },
  },
  {
    id: "P008",
    name: "Linda Martinez",
    age: 36,
    gender: "Female",
    contact: "+1 (555) 890-1234",
    email: "linda.m@email.com",
    address: "258 Spruce Ave, Schaumburg, IL",
    bloodGroup: "AB-",
    department: "Pediatrics",
    assignedDoctor: "Dr. Emily White",
    status: "Discharged",
    admissionDate: "2025-12-20",
    medicalHistory: [
      { date: "2025-12-20", diagnosis: "Child Vaccination", treatment: "MMR Vaccine Administered", doctor: "Dr. Emily White" },
    ],
    vitals: { bp: "110/70", heartRate: "68 bpm", temperature: "98.3°F", weight: "55 kg" },
  },
];

// ============ DOCTORS ============
export const doctors = [
  {
    id: "D001",
    name: "Dr. Sarah Wilson",
    specialization: "Cardiology",
    department: "Cardiology",
    qualification: "MD, FACC",
    experience: "15 years",
    contact: "+1 (555) 111-2222",
    email: "sarah.wilson@hospital.com",
    availability: "Available",
    rating: 4.8,
    patients: 120,
    schedule: { monday: "9:00 AM - 5:00 PM", tuesday: "9:00 AM - 5:00 PM", wednesday: "9:00 AM - 1:00 PM", thursday: "9:00 AM - 5:00 PM", friday: "9:00 AM - 3:00 PM" },
    image: "/doctors/doctor1.jpg",
  },
  {
    id: "D002",
    name: "Dr. Michael Chen",
    specialization: "Orthopedics",
    department: "Orthopedics",
    qualification: "MD, MS (Ortho)",
    experience: "12 years",
    contact: "+1 (555) 222-3333",
    email: "michael.chen@hospital.com",
    availability: "Available",
    rating: 4.7,
    patients: 98,
    schedule: { monday: "10:00 AM - 6:00 PM", tuesday: "10:00 AM - 6:00 PM", wednesday: "Off", thursday: "10:00 AM - 6:00 PM", friday: "10:00 AM - 4:00 PM" },
    image: "/doctors/doctor2.jpg",
  },
  {
    id: "D003",
    name: "Dr. Lisa Park",
    specialization: "Neurology",
    department: "Neurology",
    qualification: "MD, DM (Neuro)",
    experience: "18 years",
    contact: "+1 (555) 333-4444",
    email: "lisa.park@hospital.com",
    availability: "On Leave",
    rating: 4.9,
    patients: 145,
    schedule: { monday: "8:00 AM - 4:00 PM", tuesday: "8:00 AM - 4:00 PM", wednesday: "8:00 AM - 4:00 PM", thursday: "Off", friday: "8:00 AM - 2:00 PM" },
    image: "/doctors/doctor3.jpg",
  },
  {
    id: "D004",
    name: "Dr. James Brown",
    specialization: "Gastroenterology",
    department: "Gastroenterology",
    qualification: "MD, DM (Gastro)",
    experience: "10 years",
    contact: "+1 (555) 444-5555",
    email: "james.brown@hospital.com",
    availability: "Available",
    rating: 4.6,
    patients: 87,
    schedule: { monday: "9:00 AM - 5:00 PM", tuesday: "9:00 AM - 5:00 PM", wednesday: "9:00 AM - 5:00 PM", thursday: "9:00 AM - 5:00 PM", friday: "Off" },
    image: "/doctors/doctor4.jpg",
  },
  {
    id: "D005",
    name: "Dr. Amanda Lee",
    specialization: "Dermatology",
    department: "Dermatology",
    qualification: "MD, DVD",
    experience: "8 years",
    contact: "+1 (555) 555-6666",
    email: "amanda.lee@hospital.com",
    availability: "Available",
    rating: 4.5,
    patients: 76,
    schedule: { monday: "10:00 AM - 4:00 PM", tuesday: "10:00 AM - 4:00 PM", wednesday: "10:00 AM - 4:00 PM", thursday: "10:00 AM - 4:00 PM", friday: "10:00 AM - 2:00 PM" },
    image: "/doctors/doctor5.jpg",
  },
  {
    id: "D006",
    name: "Dr. Rachel Green",
    specialization: "Gynecology",
    department: "Gynecology",
    qualification: "MD, MS (OBG)",
    experience: "14 years",
    contact: "+1 (555) 666-7777",
    email: "rachel.green@hospital.com",
    availability: "Available",
    rating: 4.8,
    patients: 110,
    schedule: { monday: "9:00 AM - 3:00 PM", tuesday: "9:00 AM - 5:00 PM", wednesday: "9:00 AM - 5:00 PM", thursday: "Off", friday: "9:00 AM - 5:00 PM" },
    image: "/doctors/doctor6.jpg",
  },
  {
    id: "D007",
    name: "Dr. Emily White",
    specialization: "Pediatrics",
    department: "Pediatrics",
    qualification: "MD, DCH",
    experience: "11 years",
    contact: "+1 (555) 777-8888",
    email: "emily.white@hospital.com",
    availability: "Busy",
    rating: 4.7,
    patients: 130,
    schedule: { monday: "8:00 AM - 4:00 PM", tuesday: "8:00 AM - 4:00 PM", wednesday: "8:00 AM - 4:00 PM", thursday: "8:00 AM - 4:00 PM", friday: "8:00 AM - 12:00 PM" },
    image: "/doctors/doctor7.jpg",
  },
  {
    id: "D008",
    name: "Dr. Robert Taylor",
    specialization: "Pulmonology",
    department: "Pulmonology",
    qualification: "MD, DM (Pulmo)",
    experience: "20 years",
    contact: "+1 (555) 888-9999",
    email: "robert.taylor@hospital.com",
    availability: "Available",
    rating: 4.9,
    patients: 160,
    schedule: { monday: "9:00 AM - 5:00 PM", tuesday: "9:00 AM - 5:00 PM", wednesday: "9:00 AM - 5:00 PM", thursday: "9:00 AM - 5:00 PM", friday: "9:00 AM - 5:00 PM" },
    image: "/doctors/doctor8.jpg",
  },
];

// ============ APPOINTMENTS ============
export const appointments = [
  { id: "A001", patientName: "John Smith", patientId: "P001", doctorName: "Dr. Sarah Wilson", doctorId: "D001", department: "Cardiology", date: "2026-02-12", time: "10:00 AM", status: "Confirmed", type: "Follow-up" },
  { id: "A002", patientName: "Emily Johnson", patientId: "P002", doctorName: "Dr. Michael Chen", doctorId: "D002", department: "Orthopedics", date: "2026-02-12", time: "11:30 AM", status: "Pending", type: "Consultation" },
  { id: "A003", patientName: "Robert Davis", patientId: "P003", doctorName: "Dr. Lisa Park", doctorId: "D003", department: "Neurology", date: "2026-02-13", time: "9:00 AM", status: "Confirmed", type: "Check-up" },
  { id: "A004", patientName: "Maria Garcia", patientId: "P004", doctorName: "Dr. Amanda Lee", doctorId: "D005", department: "Dermatology", date: "2026-02-13", time: "2:00 PM", status: "Pending", type: "New Visit" },
  { id: "A005", patientName: "David Wilson", patientId: "P005", doctorName: "Dr. Sarah Wilson", doctorId: "D001", department: "Cardiology", date: "2026-02-14", time: "10:00 AM", status: "Confirmed", type: "Emergency" },
  { id: "A006", patientName: "Sarah Thompson", patientId: "P006", doctorName: "Dr. Rachel Green", doctorId: "D006", department: "Gynecology", date: "2026-02-10", time: "3:00 PM", status: "Confirmed", type: "Follow-up" },
  { id: "A007", patientName: "James Anderson", patientId: "P007", doctorName: "Dr. James Brown", doctorId: "D004", department: "Gastroenterology", date: "2026-02-09", time: "11:00 AM", status: "Completed", type: "Check-up" },
  { id: "A008", patientName: "Linda Martinez", patientId: "P008", doctorName: "Dr. Emily White", doctorId: "D007", department: "Pediatrics", date: "2026-02-08", time: "9:30 AM", status: "Completed", type: "Vaccination" },
  { id: "A009", patientName: "John Smith", patientId: "P001", doctorName: "Dr. Sarah Wilson", doctorId: "D001", department: "Cardiology", date: "2026-01-15", time: "10:00 AM", status: "Completed", type: "Consultation" },
  { id: "A010", patientName: "Emily Johnson", patientId: "P002", doctorName: "Dr. Michael Chen", doctorId: "D002", department: "Orthopedics", date: "2026-01-20", time: "2:00 PM", status: "Cancelled", type: "Follow-up" },
];

// ============ DEPARTMENTS ============
export const departments = [
  { id: "DEP001", name: "Cardiology", head: "Dr. Sarah Wilson", doctors: 8, description: "Heart and cardiovascular system care", icon: "heart", patients: 450, beds: 30 },
  { id: "DEP002", name: "Orthopedics", head: "Dr. Michael Chen", doctors: 6, description: "Musculoskeletal system treatment", icon: "bone", patients: 320, beds: 25 },
  { id: "DEP003", name: "Neurology", head: "Dr. Lisa Park", doctors: 5, description: "Brain and nervous system disorders", icon: "brain", patients: 280, beds: 20 },
  { id: "DEP004", name: "Dermatology", head: "Dr. Amanda Lee", doctors: 4, description: "Skin, hair, and nail conditions", icon: "scan", patients: 190, beds: 10 },
  { id: "DEP005", name: "Gastroenterology", head: "Dr. James Brown", doctors: 5, description: "Digestive system disorders", icon: "stethoscope", patients: 260, beds: 18 },
  { id: "DEP006", name: "Gynecology", head: "Dr. Rachel Green", doctors: 6, description: "Women's reproductive health", icon: "baby", patients: 380, beds: 22 },
  { id: "DEP007", name: "Pediatrics", head: "Dr. Emily White", doctors: 7, description: "Medical care for infants and children", icon: "baby", patients: 410, beds: 28 },
  { id: "DEP008", name: "Pulmonology", head: "Dr. Robert Taylor", doctors: 5, description: "Respiratory system and lung diseases", icon: "wind", patients: 220, beds: 15 },
  { id: "DEP009", name: "Emergency Medicine", head: "Dr. Mark Stevens", doctors: 10, description: "24/7 emergency and trauma care", icon: "siren", patients: 800, beds: 40 },
  { id: "DEP010", name: "Radiology", head: "Dr. Susan Miller", doctors: 4, description: "Medical imaging and diagnostics", icon: "scan", patients: 500, beds: 0 },
];

// ============ NOTICES ============
export const notices = [
  { id: "N001", title: "COVID-19 Vaccination Drive: April 15 - 20", date: "2026-02-08", priority: "high", category: "Health Campaign" },
  { id: "N002", title: "New Pediatric Wing Opening Soon", date: "2026-02-05", priority: "medium", category: "Infrastructure" },
  { id: "N003", title: "Health Tips: Managing Diabetes", date: "2026-02-03", priority: "low", category: "Health Tips" },
  { id: "N004", title: "Annual Health Checkup Camp - Free Registration", date: "2026-02-01", priority: "high", category: "Health Campaign" },
  { id: "N005", title: "Blood Donation Drive on February 20", date: "2026-01-28", priority: "medium", category: "Health Campaign" },
  { id: "N006", title: "New MRI Machine Installation Complete", date: "2026-01-25", priority: "low", category: "Infrastructure" },
];

// ============ MEDICAL RECORDS ============
export const medicalRecords = [
  { id: "MR001", patientId: "P001", patientName: "John Smith", type: "Blood Test", date: "2026-02-01", doctor: "Dr. Sarah Wilson", status: "Completed", fileUrl: "#" },
  { id: "MR002", patientId: "P001", patientName: "John Smith", type: "ECG Report", date: "2026-01-15", doctor: "Dr. Sarah Wilson", status: "Completed", fileUrl: "#" },
  { id: "MR003", patientId: "P002", patientName: "Emily Johnson", type: "MRI Scan", date: "2026-01-20", doctor: "Dr. Michael Chen", status: "Completed", fileUrl: "#" },
  { id: "MR004", patientId: "P003", patientName: "Robert Davis", type: "CT Scan", date: "2026-01-05", doctor: "Dr. Lisa Park", status: "Completed", fileUrl: "#" },
  { id: "MR005", patientId: "P005", patientName: "David Wilson", type: "Angiography", date: "2026-02-08", doctor: "Dr. Sarah Wilson", status: "Pending", fileUrl: "#" },
  { id: "MR006", patientId: "P004", patientName: "Maria Garcia", type: "Skin Biopsy", date: "2026-02-05", doctor: "Dr. Amanda Lee", status: "Completed", fileUrl: "#" },
  { id: "MR007", patientId: "P007", patientName: "James Anderson", type: "Endoscopy Report", date: "2026-02-03", doctor: "Dr. James Brown", status: "Pending", fileUrl: "#" },
  { id: "MR008", patientId: "P006", patientName: "Sarah Thompson", type: "Ultrasound", date: "2026-01-28", doctor: "Dr. Rachel Green", status: "Completed", fileUrl: "#" },
];

// ============ BILLING ============
export const billingRecords = [
  { id: "B001", patientId: "P001", patientName: "John Smith", date: "2026-02-01", amount: 2500, status: "Paid", insurance: "BlueCross BlueShield", insuranceCoverage: 80, description: "Cardiology Consultation + ECG", invoiceNo: "INV-2026-001" },
  { id: "B002", patientId: "P002", patientName: "Emily Johnson", date: "2026-01-20", amount: 4500, status: "Pending", insurance: "Aetna", insuranceCoverage: 70, description: "MRI Scan + Physiotherapy", invoiceNo: "INV-2026-002" },
  { id: "B003", patientId: "P003", patientName: "Robert Davis", date: "2026-01-05", amount: 3200, status: "Paid", insurance: "UnitedHealth", insuranceCoverage: 85, description: "CT Scan + Neurology Consultation", invoiceNo: "INV-2026-003" },
  { id: "B004", patientId: "P005", patientName: "David Wilson", date: "2026-02-08", amount: 15000, status: "Partial", insurance: "Cigna", insuranceCoverage: 75, description: "Emergency CPR + ICU (3 days)", invoiceNo: "INV-2026-004" },
  { id: "B005", patientId: "P004", patientName: "Maria Garcia", date: "2026-02-05", amount: 800, status: "Paid", insurance: "Humana", insuranceCoverage: 60, description: "Dermatology Consultation", invoiceNo: "INV-2026-005" },
  { id: "B006", patientId: "P007", patientName: "James Anderson", date: "2026-02-03", amount: 3800, status: "Pending", insurance: "BlueCross BlueShield", insuranceCoverage: 80, description: "Endoscopy + Medication", invoiceNo: "INV-2026-006" },
];

// ============ PHARMACY ============
export const medicines = [
  { id: "M001", name: "Amlodipine 5mg", category: "Cardiovascular", stock: 500, price: 12.99, manufacturer: "Pfizer", expiryDate: "2027-06-15", status: "In Stock" },
  { id: "M002", name: "Ibuprofen 400mg", category: "Pain Relief", stock: 1200, price: 8.50, manufacturer: "GSK", expiryDate: "2027-03-20", status: "In Stock" },
  { id: "M003", name: "Omeprazole 20mg", category: "Gastrointestinal", stock: 350, price: 15.75, manufacturer: "AstraZeneca", expiryDate: "2027-09-10", status: "In Stock" },
  { id: "M004", name: "Metformin 500mg", category: "Diabetes", stock: 800, price: 6.25, manufacturer: "Merck", expiryDate: "2027-12-01", status: "In Stock" },
  { id: "M005", name: "Cetirizine 10mg", category: "Allergy", stock: 45, price: 9.99, manufacturer: "Johnson & Johnson", expiryDate: "2027-04-30", status: "Low Stock" },
  { id: "M006", name: "Amoxicillin 500mg", category: "Antibiotic", stock: 0, price: 11.50, manufacturer: "Cipla", expiryDate: "2027-08-15", status: "Out of Stock" },
  { id: "M007", name: "Aspirin 75mg", category: "Cardiovascular", stock: 950, price: 5.99, manufacturer: "Bayer", expiryDate: "2028-01-20", status: "In Stock" },
  { id: "M008", name: "Prednisolone 5mg", category: "Corticosteroid", stock: 200, price: 18.25, manufacturer: "Pfizer", expiryDate: "2027-07-05", status: "In Stock" },
  { id: "M009", name: "Diazepam 5mg", category: "Neurological", stock: 15, price: 22.00, manufacturer: "Roche", expiryDate: "2027-02-28", status: "Low Stock" },
  { id: "M010", name: "Salbutamol Inhaler", category: "Respiratory", stock: 120, price: 35.50, manufacturer: "GSK", expiryDate: "2027-11-15", status: "In Stock" },
];

export const prescriptions = [
  { id: "RX001", patientId: "P001", patientName: "John Smith", doctorName: "Dr. Sarah Wilson", date: "2026-02-01", medicines: ["Amlodipine 5mg", "Aspirin 75mg"], status: "Active", notes: "Take after meals" },
  { id: "RX002", patientId: "P002", patientName: "Emily Johnson", doctorName: "Dr. Michael Chen", date: "2026-01-20", medicines: ["Ibuprofen 400mg"], status: "Active", notes: "Take as needed for pain" },
  { id: "RX003", patientId: "P003", patientName: "Robert Davis", doctorName: "Dr. Lisa Park", date: "2026-01-05", medicines: ["Diazepam 5mg", "Cetirizine 10mg"], status: "Completed", notes: "Complete course" },
  { id: "RX004", patientId: "P007", patientName: "James Anderson", doctorName: "Dr. James Brown", date: "2026-02-03", medicines: ["Omeprazole 20mg"], status: "Active", notes: "Take before breakfast" },
];

// ============ LABORATORY ============
export const labTests = [
  { id: "LT001", patientId: "P001", patientName: "John Smith", testName: "Complete Blood Count (CBC)", date: "2026-02-01", status: "Completed", result: "Normal", doctor: "Dr. Sarah Wilson", reportUrl: "#" },
  { id: "LT002", patientId: "P001", patientName: "John Smith", testName: "Lipid Profile", date: "2026-02-01", status: "Completed", result: "High Cholesterol", doctor: "Dr. Sarah Wilson", reportUrl: "#" },
  { id: "LT003", patientId: "P002", patientName: "Emily Johnson", testName: "X-Ray (Knee)", date: "2026-01-20", status: "Completed", result: "Mild Fracture", doctor: "Dr. Michael Chen", reportUrl: "#" },
  { id: "LT004", patientId: "P003", patientName: "Robert Davis", testName: "CT Scan (Brain)", date: "2026-01-05", status: "Completed", result: "No Abnormalities", doctor: "Dr. Lisa Park", reportUrl: "#" },
  { id: "LT005", patientId: "P005", patientName: "David Wilson", testName: "Troponin Test", date: "2026-02-08", status: "Pending", result: "-", doctor: "Dr. Sarah Wilson", reportUrl: "#" },
  { id: "LT006", patientId: "P005", patientName: "David Wilson", testName: "ECG", date: "2026-02-08", status: "Pending", result: "-", doctor: "Dr. Sarah Wilson", reportUrl: "#" },
  { id: "LT007", patientId: "P007", patientName: "James Anderson", testName: "H. Pylori Test", date: "2026-02-03", status: "Pending", result: "-", doctor: "Dr. James Brown", reportUrl: "#" },
  { id: "LT008", patientId: "P004", patientName: "Maria Garcia", testName: "Skin Biopsy", date: "2026-02-05", status: "Completed", result: "Benign", doctor: "Dr. Amanda Lee", reportUrl: "#" },
];

// ============ TELEMEDICINE ============
export const telemedicineAppointments = [
  { id: "TM001", patientName: "John Smith", patientId: "P001", doctorName: "Dr. Sarah Wilson", doctorId: "D001", date: "2026-02-12", time: "10:00 AM", status: "Scheduled", meetingLink: "#" },
  { id: "TM002", patientName: "Maria Garcia", patientId: "P004", doctorName: "Dr. Amanda Lee", doctorId: "D005", date: "2026-02-13", time: "2:00 PM", status: "Scheduled", meetingLink: "#" },
  { id: "TM003", patientName: "Emily Johnson", patientId: "P002", doctorName: "Dr. Michael Chen", doctorId: "D002", date: "2026-02-10", time: "11:00 AM", status: "In Progress", meetingLink: "#" },
  { id: "TM004", patientName: "Sarah Thompson", patientId: "P006", doctorName: "Dr. Rachel Green", doctorId: "D006", date: "2026-02-09", time: "3:00 PM", status: "Completed", meetingLink: "#" },
];

// ============ TESTIMONIALS ============
export const testimonials = [
  { id: 1, name: "Sarah M.", text: "Excellent care and great staff! The online booking was so convenient. Highly recommend!", rating: 5 },
  { id: 2, name: "Michael R.", text: "The doctors here are very professional and caring. Modern facilities and easy appointment system.", rating: 5 },
  { id: 3, name: "Jennifer K.", text: "Quick response in emergency. The telemedicine feature saved me a trip. Very satisfied!", rating: 4 },
];
